import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, Check, CreditCard, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function Pricing() {
  const [, setLocation] = useLocation();
  const settings = trpc.platform.settings.useQuery();
  const methods = [settings.data?.bkashNumber && "bKash", settings.data?.nagadNumber && "Nagad", settings.data?.rocketNumber && "Rocket", settings.data?.bankTransferInstructions && "Bank transfer"].filter(Boolean);
  return <main className="pricing-shell"><header className="pricing-nav"><Link href="/" className="brand-lockup brand-on-light"><span className="brand-mark">৳</span>Invoice<span>Pro</span></Link><Button variant="ghost" onClick={() => setLocation("/sign-in")} className="text-ink">Sign in <ArrowRight size={15} /></Button></header><section className="pricing-hero"><p className="eyebrow">SIMPLE PRICING · LOCAL PAYMENT</p><h1>Start free. Pay locally when InvoicePro starts earning its place.</h1><p>Every new customer gets 14 days to create BDT invoices, send client links, and manage follow-ups. No card is required.</p><Button size="lg" className="customer-cta max-w-xs" onClick={() => setLocation("/sign-in")}>Start your 14-day trial <ArrowRight size={17} /></Button></section><section className="public-plan-grid"><article><p className="eyebrow">SOLO</p><h2>৳500 <small>/ month</small></h2><p>For independent freelancers who want a clear payment routine.</p><ul><li><Check size={15} />Unlimited BDT invoices</li><li><Check size={15} />Client-friendly public links</li><li><Check size={15} />Follow-up queue & payment records</li></ul><Button className="secondary-button w-full" onClick={() => setLocation("/sign-in")}>Try Solo free</Button></article><article className="pro"><span>SMALL TEAM</span><p className="eyebrow">PRO</p><h2>৳1,000 <small>/ month</small></h2><p>For a growing practice that needs priority onboarding help.</p><ul><li><Check size={15} />Everything in Solo</li><li><Check size={15} />Priority setup support</li><li><Check size={15} />Early access to team features</li></ul><Button className="customer-cta" onClick={() => setLocation("/sign-in")}>Try Pro free</Button></article></section><section className="pricing-payment"><CreditCard size={22} /><div><strong>How activation works</strong><p>Choose a plan, pay with {methods.length ? methods.join(", ") : "a supported local method"}, then send your transaction reference from your InvoicePro workspace. The owner confirms access manually.</p></div><ShieldCheck size={22} /></section><Link href="/" className="pricing-back"><ArrowLeft size={15} />Back to InvoicePro</Link></main>;
}
