import StatusBadge from "@/components/StatusBadge";
import { PAYMENT_LABELS, formatBDT, formatDate } from "@/lib/invoice";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Mail, Phone, ReceiptText } from "lucide-react";
import { useEffect } from "react";
import { useRoute } from "wouter";

export default function PublicInvoice() {
  const [, params] = useRoute("/share/:token"); const token = params?.token || ""; const invoiceQuery = trpc.publicInvoice.get.useQuery({ token }, { enabled: token.length > 20 }); const markViewed = trpc.publicInvoice.markViewed.useMutation();
  useEffect(() => { if (invoiceQuery.data && !markViewed.isPending && !markViewed.isSuccess) markViewed.mutate({ token }); }, [invoiceQuery.data, markViewed, token]);
  if (invoiceQuery.isLoading) return <main className="page-loading"><div className="loading-orb" /><span>Opening invoice</span></main>; if (!invoiceQuery.data) return <main className="page-loading"><div className="auth-card"><span className="brand-mark">৳</span><h1>Invoice unavailable</h1><p>This invoice link may be incorrect or unavailable. Ask the freelancer for a new link.</p></div></main>;
  const { invoice, items, profile } = invoiceQuery.data; const methods = (["bkash", "nagad", "rocket"] as const).map(key => ({ key, value: profile[`${key}Number` as "bkashNumber" | "nagadNumber" | "rocketNumber"] })).filter(method => method.value); if (profile.bankTransferInstructions) methods.push({ key: "bank_transfer", value: profile.bankTransferInstructions } as any);
  return <main className="public-page"><header className="public-nav"><div className="brand-lockup brand-on-light"><span className="brand-mark">৳</span>Invoice<span>Pro</span></div><span className="text-xs font-bold text-slate-500">Secure invoice view</span></header><article className="public-card"><div className="public-card-top"><div className="public-business">{profile.logoUrl ? <img className="h-10 w-10 rounded-xl object-cover" src={profile.logoUrl} alt="" /> : <span className="brand-mark">৳</span>}<div><strong>{profile.businessName}</strong><span>Invoice from {profile.email}</span></div></div><StatusBadge status={invoice.status} /></div><div className="public-card-body"><div className="invoice-document-head"><div><p className="eyebrow">INVOICE</p><h2>{invoice.invoiceNumber}</h2></div><div className="doc-metadata"><p><strong>Issued</strong> {formatDate(invoice.issueDate)}</p><p><strong>Due</strong> {formatDate(invoice.dueDate)}</p></div></div><div className="bill-to"><small>BILL TO</small><h3>{invoice.clientName}</h3><p>{[invoice.clientEmail, invoice.clientPhone, invoice.clientAddress].filter(Boolean).join("\n")}</p></div><table className="doc-table"><thead><tr><th>Description</th><th>Quantity</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.description}</td><td>{item.quantityHundredths / 100}</td><td>{formatBDT(item.unitAmountPaisa)}</td><td>{formatBDT(item.lineTotalPaisa)}</td></tr>)}</tbody></table><div className="doc-total"><div><span>Subtotal</span><strong>{formatBDT(invoice.subtotalPaisa)}</strong></div>{invoice.discountPaisa > 0 && <div><span>Discount</span><strong>− {formatBDT(invoice.discountPaisa)}</strong></div>}<div><span>Total due</span><strong>{formatBDT(invoice.totalPaisa)}</strong></div></div>{invoice.notes && <p className="mt-6 border-t border-slate-100 pt-5 text-sm leading-6 text-slate-600">{invoice.notes}</p>}<section className="public-payment"><h3>Payment instructions</h3><p className="mt-1 text-xs text-slate-500">Pay the freelancer directly using one of the methods below.</p>{methods.length ? <div className="payment-grid">{methods.map((method: any) => <div key={method.key} className="payment-option"><strong>{PAYMENT_LABELS[method.key as keyof typeof PAYMENT_LABELS]}</strong><span>{method.value}</span></div>)}</div> : <p className="mt-3 text-xs text-slate-500">Please contact the freelancer for payment instructions.</p>}</section><div className="mt-5 flex flex-wrap gap-3 border-t border-slate-100 pt-5 text-xs text-slate-500"><span className="flex items-center gap-1"><Mail size={13} />{profile.email}</span><span className="flex items-center gap-1"><Phone size={13} />{profile.phone}</span></div></div></article><p className="public-footer"><CheckCircle2 size={12} className="mr-1 inline text-[#0f766e]" />This link is public so you can view it without creating an account. Powered by <a href="/">InvoicePro</a>.</p></main>;
}
